CREATE TABLE `version_info_del` (
  `ref` INT(11) NOT NULL AUTO_INCREMENT COMMENT '流水',
  `version_id` INT(11) NOT NULL COMMENT '版本',
  `version_name` VARCHAR(500) NOT NULL COMMENT '版本名称',
  `cont_desc` VARCHAR(500) DEFAULT NULL COMMENT '描述',
  `abbreviation` VARCHAR(200) DEFAULT NULL COMMENT '版本简称',
  `is_only_for_primark` INT(1) NOT NULL DEFAULT '0' COMMENT '是否只用于小学,0:否，1：是',
  `subject_id` INT(11) NOT NULL COMMENT '学科',
  `section_id` INT(11) DEFAULT NULL COMMENT '学段',
  `c_time` DATETIME NOT NULL,
  `c_user_id` INT(11) DEFAULT NULL,
  `m_time` DATETIME DEFAULT NULL,
  `m_user_id` INT(11) DEFAULT NULL,
  `active` INT(1) NOT NULL DEFAULT '1' COMMENT '有效状态，1:有效 0:无效',
  `ggs_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ref`),
  KEY `idx_vid` (`version_id`),
  KEY `idx_subject_id` (`subject_id`),
  KEY `idx_section_id` (`section_id`)
) ENGINE=INNODB DEFAULT CHARSET=gbk